### PR TITLE
NETOBSERV-1245: NETOBSERV-1304: fix TCP DNS query

### PR DESCRIPTION
**Pull request by msherif1234**
## Description

Tracking DNS over TCP was impossible using tracepoints as the dns hdr never exists in the 1st segment and when use ebpf TP there are no helpers to get to packet from the following segments

Solution was to do DNS tracking inline with TC hook and to gain better accuracy for all NDS queries its needed to run with sampling of 1
image

image

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Will this change affect NetObserv / Network Observability operator? If not, you can ignore the rest of this checklist.
* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [X] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by msherif1234** [comment]
image

**Review by jpinsonneau — APPROVED** [review]
That's awesome ! thanks @msherif1234 

Do you expect better performances since the DNS tracepoint is not used anymore ? 
As followup, should we have a separated `sampling` per feature (DNS / RTT) ? Or is there a way to avoid having sampling `1` to make it accurate.

**Comment by msherif1234** [comment]
cc'd @Amoghrd

**Comment by msherif1234** [comment]
> That's awesome ! thanks @msherif1234
> 
> Do you expect better performances since the DNS tracepoint is not used anymore ? As followup, should we have a separated `sampling` per feature (DNS / RTT) ? Or is there a way to avoid having sampling `1` to make it accurate.

its not only for DNS/RTT even for the regular TC flows if sampling not 1 won't get very accurate latency as well, I spoke with @jotak and he told me for customers who are looking for accurate analysis its expected/encouraged to use sampling of `1`

**Pull request merged**
