### PR TITLE
NETOBSERV-1151: move flp decode grpc pipe to netobserv agent to avoid flp code updates

### PR DESCRIPTION
**Pull request by msherif1234**
move FLP grpc decode logic to the agent to just limit flp to pkg update w/o need to do any code changes

### CODE REVIEW

**Comment by Amoghrd** [comment]
Ran the full-suite of automated regression tests for the above eBPF image. All except SCTP test-case passed(which is known issue, being investigated; issue unrelated to this PR). [204887](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/204887/console)

**Comment by Amoghrd** [comment]
Also regression tested the PacketDrop feature and its working as expected!

**Review by jpinsonneau — APPROVED** [review]
Code looks good, `decode_protobuf.go` is up to date right now. I would suggest to merge to avoid having to sync it again and again :smile_cat:

**Pull request merged**
