### PR TITLE
 NETOBSERV-1107: Update cilium to v0.11.0

### PR DESCRIPTION
**Pull request by msherif1234**
https://github.com/cilium/ebpf/releases/tag/v0.11.0

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM, @msherif1234 does it requires special testing ? Have you noticed a performance impact ?

cc: @memodi

**Comment by msherif1234** [comment]
> LGTM, @msherif1234 does it requires special testing ? Have you noticed a performance impact ?
> 
> cc: @memodi

Bringing up cluster now to check on performance there are some optimizations in this release hopefully will show something will update pr with performance results

**Comment by jpinsonneau** [comment]
> No just passing e2e and manual testing on cluster-bot is sufficient, performance attached below memory looks much better cpu is about the same

25% memory gain :partying_face: 
Have you checked the records output count to ensure it's similar & dropped count is still 0 ?

**Comment by memodi** [comment]
@msherif1234 @jpinsonneau - is there a JIRA tracking this change? cc @nathan-weinberg

**Comment by msherif1234** [comment]
> @msherif1234 @jpinsonneau - is there a JIRA tracking this change? cc @nathan-weinberg

this is more of tech dept no JIRA

**Comment by davegord** [comment]
Correct JIRA tracker is https://issues.redhat.com//browse/NETOBSERV-1107

**Pull request merged**
